### PR TITLE
bugfix/incorrect `redirect_uri` query param in OAuth2 implicit authentication

### PR DESCRIPTION
**Pull request by Canecat**
added support of `oauth2RedirectUrl` swagger UI config parameter
updated Config struct
added new config helpers
updated tests
updated readme

### CODE REVIEW

**Comment by Canecat** [comment]
Hello @easonlin404.

If we want to use OAuth2 implicit flow then we need to set `@authorizationUrl` and client_id. 
After user click the "Authorize" button, Swagger UI opens this `authorizationUrl` with several query parameters (e.g. https://example.com/authentication/login?response_type=token&client_id=localhost.example.com&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fapi%2Fv1%2Fswagger%2Foauth2-redirect.html...).
`redirect_uri` query parameter says where user should be redirected by OAuth provider after successful authorization. Swagger UI must process in 'oauth2-redirect.html' and store `autorization_token`returned by provider, to be able to set `Authorization` header in API calls which need authorization. That's how this flow should work.

By default `oauth2RedirectUrl` is calculated by Swagger UI as `${window.location.protocol}//${window.location.host}/oauth2-redirect.html` e.g. 'http://localhost:8000/oauth2-redirect.html' which is not correct in most cases because Swagger UI is usually hosted under some sub route (e.g. '/api/v1/swagger/'). 
So we should set this swagger config parameter to correct location of `oauth2-redirect.html`, if we want to be able to call API endpoints which need authorization.

Thank you for quick response.

**Comment by Canecat** [comment]
Hi @easonlin404, any updates?

**Comment by vovailchenko** [comment]
@easonlin404 i've just come across the same issue as described in https://github.com/swaggo/gin-swagger/pull/92#issuecomment-559444761
in short - when serving a swagger ui at `swagger-host/swagger`, and when using implicit flow from oidc provider (i'm using self-hosted keycloak) - redirect from keycloak is going to `swagger-host/oauth2-redirect.html` - but should be going to `swagger-host/swagger/oauth2-redirect.html`
i've just tested this and it's working for the implicit flow

image
Please advise on what is needed to merge this, i'm eager to contribute if i will be able to

**Comment by vovailchenko** [comment]
@Canecat @easonlin404 i've just checked and the issue is reproduced not only with the Implicit Grant. It's as well visible with the **Authorization Code Grant (which is currently considered as a best practice).** 
Will switch to [https://github.com/Canecat/gin-swagger](url) for a time being, but i would really like to see this PR accepted

**Comment by Jurabek** [comment]
@Canecat please use `window.location.href` instead `${window.location.protocol}//${window.location.host}" + filepath.Join(config.SwaggerBase, "oauth2-redirect.html") + "` it is two many code here, `window.location.href` includes `basePath` too. [here is dotnet swagger implementation of this problem](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/index.html)

**Comment by ubogdan** [comment]
@Canecat Please resolve the conflicts and I will try to do a review after that.

**Comment by jolbax-sbb** [comment]
Looking for this bugfix to be released. 🙏

**Review by jolbax-sbb — APPROVED** [review]

**Comment by ubogdan** [comment]
Closing reason: Outdated.

**Pull request closed without merging**
