### PR TITLE
Fix oauth2-redirect outside of the base swagger path

### PR DESCRIPTION
**Pull request by alvarogf97**
**Problem**

When you use Oaut2 implicit flow, swagger ui sends an url that not includes the path where the swagger ui is located  to the authorization page

If you include swaggo in your project like this:
```go
router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
```
You will get this redirect url in the oauth2 implicit flow:
```
{protocol}//{host}/oauth2-redirect.html
```
This url is not found due to his location is `{protocol}//{host}/swagger/oauth2-redirect.html`
actually

**Relation issue**
The issue is #115

**Additional context**
I add the minimun changes to make it work.

PD: sorry for the other changes fmt did his work :D and I think it could be worth

cc: @ubogdan @DeyiXu

The following images belong to my own project that can be a proof of how it works
url1
url2

Sorry for my broken english, I'm from Spain :D

### CODE REVIEW

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@alvarogf97 Thanks for your contribution.

**Comment by alvarogf97** [comment]
thanks for merging @ubogdan 

Could you create a new package release? Thanks!

**Comment by ubogdan** [comment]
added v1.3.3

**Comment by DeyiXu** [comment]
Thanks contribution

**Pull request merged**
