### PR TITLE
chore: update generated doc import

### LINKED ISSUE #56: Does this work with vgo?
Hi, following the instructions, but _ "./docs" doesn´t seem to be foundable. Could it be because we are using vgo modules and the project is not in the $GOPATH?
Is there any doc on how to go around this?

Thanks!

### PR DESCRIPTION
**Pull request by easonlin404**
closes #56

### CODE REVIEW

**Comment by easonlin404** [comment]
@ubogdan Please help review.

**Comment by ubogdan** [comment]
i think something is wrong ... I aproved it 3 times till now.

**Comment by easonlin404** [comment]
@ubogdan yo don't see the following merge button?
螢幕快照 2019-07-16 下午6 28 19

**Comment by easonlin404** [comment]
@ubogdan  ah my mistake, please re-approved and squash/merge it.

**Comment by ubogdan** [comment]
Done

**Pull request merged**
