### PR TITLE
fix: update gin-contrib/gzip to latest version

### PR DESCRIPTION
**Pull request by venu-prasanna-tw**
We are using the latest version of [github.com/swaggo/gin-swagger@v1.5.0] which internally uses the gin-contrib/gzip library and the version is [github.com/gin-contrib/gzip@v0.0.5] in go.mod

This has introduced snyk vulnerability HTTP Response Splitting with the following path:
github.com/swaggo/gin-swagger@v1.5.0 › github.com/gin-contrib/gzip@v0.0.5 › github.com/gin-gonic/gin@v1.7.4

Snyk issue link: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736

In order to solve this issue I have upgraded gin-contrib/gzip to latest version.

### CODE REVIEW

**Comment by ubogdan** [comment]
@venu-prasanna-tw Thanks for your contribution.

**Comment by ruchi-dhore-tw** [comment]
@ubogdan any idea when this change would be released?

**Comment by ubogdan** [comment]
released.

**Comment by ruchi-dhore-tw** [comment]
Thank you @ubogdan !

**Pull request merged**
