### PR TITLE
Update ugorji/go dependency

### LINKED ISSUE #128: go: github.com/ugorji/go@v1.1.5-pre: unknown revision v1.1.5-pre
Have problem with `go mod download` in project using gin-swagger:

```
go: github.com/ugorji/go@v1.1.5-pre: unknown revision v1.1.5-pre
go: error loading module requirements
```

As I see gin-swagger still use ugorji 1.1.5-pre but this tag is not exists now:

https://github.com/swaggo/gin-swagger/blob/0be48022e8f0d35d979643d8e36032a865cb33f4/go.mod#L13

```
github.com/ugorji/go v1.1.5-pre // indirect
```

This helped me:

```
replace github.com/ugorji/go v1.1.5-pre => github.com/ugorji/go v1.1.7
```

But would be better to update dependencies in this project. Thanks.

### PR DESCRIPTION
**Pull request by ffenix113**
Fixes #128

### CODE REVIEW

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@ffenix113 Thanks for your contribution.

**Comment by ffenix113** [comment]
Thank you @ubogdan !

Would it be possible to create a new patch tag? This change also should fix broken swaggo/swag repo(and probably others also which don't use Golang proxy).

**Comment by ubogdan** [comment]
tag v1.3.0 added

**Pull request merged**
